const ProjectData = [
  {
    id: 1,
    title: "Smart Vision",
    img: "https://picsum.photos/id/1011/600/400",
    category: "AI / Machine Learning",
    desc: "Developed an AI-based vision system for real-time object detection and tracking using TensorFlow and React.",
    tech: ["React", "TensorFlow", "Tailwind CSS"],
    live: "https://smartvision-demo.com",
    github: "https://github.com/username/smartvision",
  },
  {
    id: 2,
    title: "E-Commerce Platform",
    img: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=tinysrgb&fit=crop&w=600&h=400",
    category: "Web Development",
    desc: "Built a scalable e-commerce website with product filtering, admin dashboard, and Stripe payment integration.",
    tech: ["React", "Node.js", "MongoDB"],
    live: "https://ecommerce-demo.com",
    github: "https://github.com/username/ecommerce-platform",
  },
  {
    id: 3,
    title: "Portfolio Website",
    img: "https://picsum.photos/id/1005/600/400",
    category: "UI/UX Design",
    desc: "Designed and developed a responsive personal portfolio website to showcase projects and blogs with animations.",
    tech: ["HTML", "CSS", "JavaScript"],
    live: "https://username-portfolio.com",
    github: "https://github.com/username/portfolio",
  },
  {
    id: 4,
    title: "Restaurant Booking",
    img: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?crop=entropy&cs=tinysrgb&fit=crop&w=600&h=400",
    category: "Mobile Development",
    desc: "Created a cross-platform restaurant table booking app with Firebase authentication and real-time updates.",
    tech: ["React Native", "Firebase"],
    live: "https://restaurantapp-demo.com",
    github: "https://github.com/username/restaurant-booking-app",
  },
  {
    id: 5,
    title: "Chat Application",
    img: "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7?crop=entropy&cs=tinysrgb&fit=crop&w=600&h=400",
    category: "Full Stack Development",
    desc: "Developed a real-time chat application with socket.io, supporting private and group messaging.",
    tech: ["Node.js", "Socket.io", "React"],
    live: "https://chatapp-demo.com",
    github: "https://github.com/username/chatapp",
  },
  {
    id: 6,
    title: "Finance Dashboard",
    img: "https://images.unsplash.com/photo-1556157382-97eda2d62296?crop=entropy&cs=tinysrgb&fit=crop&w=600&h=400",
    category: "Data Visualization",
    desc: "Built an interactive finance dashboard displaying dynamic charts and analytics using Chart.js.",
    tech: ["React", "Chart.js", "Tailwind CSS"],
    live: "https://financedashboard-demo.com",
    github: "https://github.com/username/finance-dashboard",
  },
  {
    id: 7,
    title: "Travel Blog Website",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?crop=entropy&cs=tinysrgb&fit=crop&w=600&h=400",
    category: "Web Design",
    desc: "Designed a visually engaging travel blog website with a focus on imagery and minimalistic layout.",
    tech: ["HTML", "CSS", "JavaScript"],
    live: "https://travelblog-demo.com",
    github: "https://github.com/username/travelblog",
  },
  {
    id: 8,
    title: "Task Management Tool",
    img: "https://images.unsplash.com/photo-1557804506-669a67965ba0?crop=entropy&cs=tinysrgb&fit=crop&w=600&h=400",
    category: "Productivity App",
    desc: "Developed a task management web app with features like kanban boards, deadlines, and team assignments.",
    tech: ["React", "Redux", "Firebase"],
    live: "https://taskmanager-demo.com",
    github: "https://github.com/username/taskmanager",
  },
];

export default ProjectData;
